---
abstract: 'efficient shared mutable hash'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Data::Dumper: '0'
  Errno: '1.00'
  ExtUtils::CBuilder: '0.15'
  ExtUtils::ParseXS: '3.24'
  File::Temp: '0.22'
  IO::File: '0'
  Module::Build: '0'
  POSIX: '0'
  Scalar::String: '0'
  Test::Builder: '0.03'
  Test::More: '0.40'
  if: '0'
  perl: '5.006'
  strict: '0'
  utf8: '0'
  warnings: '0'
configure_requires:
  Module::Build: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hash-SharedMem
provides:
  Hash::SharedMem:
    file: lib/Hash/SharedMem.pm
    version: '0.005'
  Hash::SharedMem::Handle:
    file: lib/Hash/SharedMem/Handle.pm
    version: '0.005'
recommends:
  Devel::CallChecker: '0.003'
requires:
  Exporter: '0'
  XSLoader: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Hash-SharedMem
  license: http://dev.perl.org/licenses/
version: '0.005'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
